apiVersion: apps/v1
kind: Deployment
metadata:
  name: rserve-deployment
  labels:
    app: rserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rserve
  template:
    metadata:
      labels:
        app: rserve
    spec:
      containers:
      - name: rserve
        image: acrdataverse0913.azurecr.io/rserve:dataverse
        ports:
        - containerPort: 6311
---
apiVersion: v1
kind: Service
metadata:
  name: rserve-service
spec:
  selector:
    app: rserve
  ports:
    - protocol: TCP
      port: 6311
      targetPort: 6311